services:
  - type: web
    name: poker-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 --log-file=- -b 0.0.0.0:$PORT app:app --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
    healthCheckPath: /health
    healthCheckTimeout: 10
