services:
  - type: web
    name: poker-game
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_simple.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"
    plan: free
